FROM node:26-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --config.minimum-release-age=0

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]